language: java
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
  - echo Ready...
install: echo Set...
before_script: echo Go!
script: ./gradlew build
before_deploy:
  - export JAR_NAME=$(ls rpgportal.app/build/libs/rpgportal.app-*.jar)
deploy:
  provider: boxfuse
  payload: $JAR_NAME
  image: rpgportal:$TRAVIS_BUILD_NUMBER
  extra_args: "-app=rpgportal -debug=true -logs.tail=true"
after_deploy:
  - boxfuse/boxfuse rm rpgportal:($TRAVIS_BUILD_NUMBER-1) -vault
  - echo Deployed!
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/