language: java
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
  - echo Ready...
install: echo Set...
before_script: echo Go!
script: ./gradlew build
before_deploy:
  - export JAR_NAME=$(ls rpgportal.app/build/libs/rpgportal.app-*.jar)
deploy:
  provider: boxfuse
  payload: $JAR_NAME
  app: 'rpgportal'
  debug: true
  logsTail: true
after_deploy: echo Deployed!
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/