language: java
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
  - echo Ready...
install: echo Set...
before_script: echo Go!
script: ./gradlew build
before_deploy:
  - export JAR_NAME=$(ls rpgportal.app/build/libs/rpgportal.app-*.jar)
deploy:
  provider: boxfuse
  payload: $JAR_NAME
  image: rpgportal:$TRAVIS_BUILD_NUMBER
  extra_args: "-app=rpgportal -debug=true -ports.http=80 -logs=true -logs.auto=true -logs.dir=boxfuse -logs.tail=true -envvars.SPRING_PROFILES_ACTIVE=$BOXFUSE_ENV"
after_deploy:
  - chmod +x deploy/afterDeploy.sh
  - ./deploy/afterDeploy.sh
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/