language: java
jdk: oraclejdk8
before_install: chmod +x gradlew
install: ./gradlew assemble
script: ./gradlew check
before_deploy:
  - export JAR_NAME=$(ls rpgportal.app/build/libs/rpgportal.app-*.jar)
deploy:
  provider: boxfuse
  payload: $JAR_NAME
  image: rpgportal:$TRAVIS_BUILD_NUMBER
  extra_args: "-app=rpgportal -debug=true -ports.http=80 -ports.debug=5005 -healthcheck.timeout=120 -logs=true -logs.auto=true -logs.dir=boxfuse -logs.tail=true -envvars.SPRING_PROFILES_ACTIVE=test"
after_deploy:
  - chmod +x deploy/afterDeploy.sh
  - ./deploy/afterDeploy.sh || travis_terminate 1;
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  webhooks:
    urls:
      - https://hooks.glip.com/webhook/0907b545-2cfc-4476-bcd3-3a5ff1001e57