language: java
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
script: ./gradlew build
deploy:
  provider: boxfuse
  payload: "rpgportal.app/build/libs/rpgportal.app-$TRAVIS_BUILD_NUMBER.jar"
after_deploy: echo Deployed!