language: java
jdk: oraclejdk8
before_install: echo Ready...
install: echo Set...
before_script: echo Go!
script: ./gradlew build
deploy:
  provider: boxfuse
  payload: "rpgportal.app/build/libs/rpgportal.app-$TRAVIS_BUILD_NUMBER.jar"
after_deploy: echo Deployed!